// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GeneralParamsInput struct {
	AccessToken *string `json:"accessToken,omitempty"`
	CompanyUUID *string `json:"companyUuid,omitempty"`
	IdmUserUUID *string `json:"idmUserUuid,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type TipicalKafkaResponse struct {
	EventUUID string `json:"eventUuid"`
}

type TipicalMutationResponse struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type TipicalQueryResponse struct {
	UUID *string `json:"uuid,omitempty"`
}
