package graph_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"errors"

	"github.com/testovoleg/5s-microservice-template/graphql_service/internal/app/commands"
	"github.com/testovoleg/5s-microservice-template/graphql_service/internal/graph_model"
	graph "github.com/testovoleg/5s-microservice-template/graphql_service/schema"
	"github.com/testovoleg/5s-microservice-template/pkg/constants"
	"github.com/testovoleg/5s-microservice-template/pkg/metrics"
	"github.com/testovoleg/5s-microservice-template/pkg/tracing"
)

// TmpTipicalMutation is the resolver for the tmp_tipicalMutation field.
func (r *mutationResolver) TmpTipicalMutation(ctx context.Context, input model.GeneralParamsInput) (*model.TipicalMutationResponse, error) {
	r.metrics.Get("TipicalMutation", metrics.GRAPHQL).Inc()

	ctx, span := tracing.StartGrpcServerTracerSpan(ctx, "mutationResolver.TipicalMutation")
	defer span.End()

	token, ok := ctx.Value(constants.ContextKeyToken).(string)
	if !ok {
		return nil, errors.New("can't find token")
	}

	input.AccessToken = &token

	command := &commands.PostTipicalMutationCommand{Params: &input}

	err := r.bs.Commands.PostTipicalMutation.Handle(ctx, command)
	if err != nil {
		r.log.WarnMsg("mutationResolver.TipicalMutation", err)
		r.metrics.Get("Error", metrics.GRAPHQL).Inc()

		return &model.TipicalMutationResponse{
			Code:    400,
			Success: false,
			Message: err.Error(),
		}, nil
	}

	r.metrics.Get("Success", metrics.GRAPHQL).Inc()
	return &model.TipicalMutationResponse{
		Code:    200,
		Success: true,
		Message: "",
	}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
