package graph_resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"errors"

	"github.com/testovoleg/5s-microservice-template/graphql_service/internal/app/commands"
	"github.com/testovoleg/5s-microservice-template/graphql_service/internal/graph_model"
	graph "github.com/testovoleg/5s-microservice-template/graphql_service/schema"
	"github.com/testovoleg/5s-microservice-template/pkg/constants"
	"github.com/testovoleg/5s-microservice-template/pkg/metrics"
	"github.com/testovoleg/5s-microservice-template/pkg/tracing"
	"go.opentelemetry.io/otel/codes"
)

// TmpTipicalData is the resolver for the tmp_tipicalData field.
func (r *queryResolver) TmpTipicalData(ctx context.Context, params *model.GeneralParamsInput) (*model.TipicalQueryResponse, error) {
	r.metrics.Get("TipicalData", metrics.GRAPHQL).Inc()

	ctx, span := tracing.StartGrpcServerTracerSpan(ctx, "queryResolver.CarsList")
	defer span.End()

	token, ok := ctx.Value(constants.ContextKeyToken).(string)
	if !ok {
		return nil, errors.New("can't find token")
	}

	params.AccessToken = &token

	command := &commands.GetTipicalDataCommand{Params: params}

	response, err := r.bs.Commands.GetTipicalData.Handle(ctx, command)
	if err != nil {
		r.log.WarnMsg("queryResolver.CarsList", err)
		r.metrics.Get("Error", metrics.GRAPHQL).Inc()
		span.SetStatus(codes.Error, "operation in gql failed")
		span.RecordError(err)
		return nil, err
	}

	r.metrics.Get("Success", metrics.GRAPHQL).Inc()
	span.SetStatus(codes.Ok, "operation in gql complete")
	return response, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
