// Version: 1.0.29
// Last changes: Add option CreateRoom & COMPANY channel
// Last changes: Add Content UTM
// Last changes: Add Channel MAX_USER
// Last changes: Add EventType CACHE
// Last changes: Add Channel MAX
// Last changes: Add option ParseMode
// Last changes: Add Channel AVITO
// Last changes: Add EventType NEW_CHAT
// Last changes: Add EventType NEW_BOT
// Last changes: Add EventType DATA_SIGN
// Last changes: Make Gateway.Channel optional
// Last changes: Add some variables to buttons

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: events.proto

package kafkaMessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_UNKNOWN      EventType = 0
	EventType_MESSAGE      EventType = 1
	EventType_CALLBACK     EventType = 2
	EventType_EVT_STATE    EventType = 3
	EventType_ROOM_OPTIONS EventType = 4
	EventType_TEXT_TYPING  EventType = 5
	EventType_ATTACH_FILES EventType = 6
	EventType_ARCHIVE      EventType = 7
	EventType_NEW_BOT      EventType = 8
	EventType_NEW_CHAT     EventType = 9
	EventType_MESSAGE_EDIT EventType = 10
	EventType_DATA_SIGN    EventType = 11
	EventType_CACHE        EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "MESSAGE",
		2:  "CALLBACK",
		3:  "EVT_STATE",
		4:  "ROOM_OPTIONS",
		5:  "TEXT_TYPING",
		6:  "ATTACH_FILES",
		7:  "ARCHIVE",
		8:  "NEW_BOT",
		9:  "NEW_CHAT",
		10: "MESSAGE_EDIT",
		11: "DATA_SIGN",
		12: "CACHE",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":      0,
		"MESSAGE":      1,
		"CALLBACK":     2,
		"EVT_STATE":    3,
		"ROOM_OPTIONS": 4,
		"TEXT_TYPING":  5,
		"ATTACH_FILES": 6,
		"ARCHIVE":      7,
		"NEW_BOT":      8,
		"NEW_CHAT":     9,
		"MESSAGE_EDIT": 10,
		"DATA_SIGN":    11,
		"CACHE":        12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_INCOMING  Direction = 0
	Direction_OUTCOMING Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "INCOMING",
		1: "OUTCOMING",
	}
	Direction_value = map[string]int32{
		"INCOMING":  0,
		"OUTCOMING": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type FileType int32

const (
	FileType_SOMETHING FileType = 0
	FileType_PHOTO     FileType = 1
	FileType_IMAGE     FileType = 2
	FileType_DOC       FileType = 3
	FileType_AUDIO     FileType = 4
	FileType_VIDEO     FileType = 5
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "SOMETHING",
		1: "PHOTO",
		2: "IMAGE",
		3: "DOC",
		4: "AUDIO",
		5: "VIDEO",
	}
	FileType_value = map[string]int32{
		"SOMETHING": 0,
		"PHOTO":     1,
		"IMAGE":     2,
		"DOC":       3,
		"AUDIO":     4,
		"VIDEO":     5,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[2].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[2]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

type Channel int32

const (
	Channel_EMPTY_CHANNEL Channel = 0
	Channel_TELEGRAM      Channel = 1
	Channel_VK            Channel = 2
	Channel_WABA          Channel = 3
	Channel_WEB           Channel = 4
	Channel_WHATSAPP      Channel = 5
	Channel_AVITO         Channel = 6
	Channel_MAX           Channel = 7
	Channel_MAX_USER      Channel = 8
	Channel_COMPANY       Channel = 9
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "EMPTY_CHANNEL",
		1: "TELEGRAM",
		2: "VK",
		3: "WABA",
		4: "WEB",
		5: "WHATSAPP",
		6: "AVITO",
		7: "MAX",
		8: "MAX_USER",
		9: "COMPANY",
	}
	Channel_value = map[string]int32{
		"EMPTY_CHANNEL": 0,
		"TELEGRAM":      1,
		"VK":            2,
		"WABA":          3,
		"WEB":           4,
		"WHATSAPP":      5,
		"AVITO":         6,
		"MAX":           7,
		"MAX_USER":      8,
		"COMPANY":       9,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[3].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[3]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

type EventState int32

const (
	EventState_UNKNOWN_STATE EventState = 0
	EventState_CREATED       EventState = 1
	EventState_SENT          EventState = 2
	EventState_RECEIVED      EventState = 3
	EventState_READ          EventState = 4
	EventState_ERROR         EventState = 5
)

// Enum value maps for EventState.
var (
	EventState_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "CREATED",
		2: "SENT",
		3: "RECEIVED",
		4: "READ",
		5: "ERROR",
	}
	EventState_value = map[string]int32{
		"UNKNOWN_STATE": 0,
		"CREATED":       1,
		"SENT":          2,
		"RECEIVED":      3,
		"READ":          4,
		"ERROR":         5,
	}
)

func (x EventState) Enum() *EventState {
	p := new(EventState)
	*p = x
	return p
}

func (x EventState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventState) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[4].Descriptor()
}

func (EventState) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[4]
}

func (x EventState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventState.Descriptor instead.
func (EventState) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

type AttachFilesAction int32

const (
	AttachFilesAction_EMPTY_ACTION_ATTACH_FILES AttachFilesAction = 0
	AttachFilesAction_TASK_ADD                  AttachFilesAction = 1
	AttachFilesAction_TASK_DONE                 AttachFilesAction = 2
)

// Enum value maps for AttachFilesAction.
var (
	AttachFilesAction_name = map[int32]string{
		0: "EMPTY_ACTION_ATTACH_FILES",
		1: "TASK_ADD",
		2: "TASK_DONE",
	}
	AttachFilesAction_value = map[string]int32{
		"EMPTY_ACTION_ATTACH_FILES": 0,
		"TASK_ADD":                  1,
		"TASK_DONE":                 2,
	}
)

func (x AttachFilesAction) Enum() *AttachFilesAction {
	p := new(AttachFilesAction)
	*p = x
	return p
}

func (x AttachFilesAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachFilesAction) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[5].Descriptor()
}

func (AttachFilesAction) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[5]
}

func (x AttachFilesAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachFilesAction.Descriptor instead.
func (AttachFilesAction) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

type ArchiveAction int32

const (
	ArchiveAction_EMPTY_ACTION_ARCHIVE ArchiveAction = 0
	ArchiveAction_MOVE_TO_ARCHIVE      ArchiveAction = 1
	ArchiveAction_RETURN_FROM_ARCHIVE  ArchiveAction = 2
)

// Enum value maps for ArchiveAction.
var (
	ArchiveAction_name = map[int32]string{
		0: "EMPTY_ACTION_ARCHIVE",
		1: "MOVE_TO_ARCHIVE",
		2: "RETURN_FROM_ARCHIVE",
	}
	ArchiveAction_value = map[string]int32{
		"EMPTY_ACTION_ARCHIVE": 0,
		"MOVE_TO_ARCHIVE":      1,
		"RETURN_FROM_ARCHIVE":  2,
	}
)

func (x ArchiveAction) Enum() *ArchiveAction {
	p := new(ArchiveAction)
	*p = x
	return p
}

func (x ArchiveAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchiveAction) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[6].Descriptor()
}

func (ArchiveAction) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[6]
}

func (x ArchiveAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchiveAction.Descriptor instead.
func (ArchiveAction) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventUUID     string                 `protobuf:"bytes,1,opt,name=EventUUID,proto3" json:"EventUUID,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,2,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=Direction,proto3,enum=kafkaMessages.Direction" json:"Direction,omitempty"`
	Type          EventType              `protobuf:"varint,4,opt,name=Type,proto3,enum=kafkaMessages.EventType" json:"Type,omitempty"`
	From          *Contact               `protobuf:"bytes,5,opt,name=From,proto3,oneof" json:"From,omitempty"`
	Content       *Content               `protobuf:"bytes,6,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	EventStates   *EventStates           `protobuf:"bytes,8,opt,name=EventStates,proto3,oneof" json:"EventStates,omitempty"`
	RoomOptions   *RoomOptions           `protobuf:"bytes,9,opt,name=RoomOptions,proto3,oneof" json:"RoomOptions,omitempty"`
	TextTyping    *TextTyping            `protobuf:"bytes,10,opt,name=TextTyping,proto3,oneof" json:"TextTyping,omitempty"`
	AttachFiles   *AttachFiles           `protobuf:"bytes,11,opt,name=AttachFiles,proto3,oneof" json:"AttachFiles,omitempty"`
	Archive       *Archive               `protobuf:"bytes,12,opt,name=Archive,proto3,oneof" json:"Archive,omitempty"`
	ReplyTo       *string                `protobuf:"bytes,13,opt,name=ReplyTo,proto3,oneof" json:"ReplyTo,omitempty"`
	Cache         *Cache                 `protobuf:"bytes,14,opt,name=Cache,proto3,oneof" json:"Cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventUUID() string {
	if x != nil {
		return x.EventUUID
	}
	return ""
}

func (x *Event) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Event) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_INCOMING
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_UNKNOWN
}

func (x *Event) GetFrom() *Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Event) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetEventStates() *EventStates {
	if x != nil {
		return x.EventStates
	}
	return nil
}

func (x *Event) GetRoomOptions() *RoomOptions {
	if x != nil {
		return x.RoomOptions
	}
	return nil
}

func (x *Event) GetTextTyping() *TextTyping {
	if x != nil {
		return x.TextTyping
	}
	return nil
}

func (x *Event) GetAttachFiles() *AttachFiles {
	if x != nil {
		return x.AttachFiles
	}
	return nil
}

func (x *Event) GetArchive() *Archive {
	if x != nil {
		return x.Archive
	}
	return nil
}

func (x *Event) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *Event) GetCache() *Cache {
	if x != nil {
		return x.Cache
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUUID   string                 `protobuf:"bytes,1,opt,name=CompanyUUID,proto3" json:"CompanyUUID,omitempty"`
	Channel       *Channel               `protobuf:"varint,2,opt,name=Channel,proto3,enum=kafkaMessages.Channel,oneof" json:"Channel,omitempty"`
	BotUUID       string                 `protobuf:"bytes,3,opt,name=BotUUID,proto3" json:"BotUUID,omitempty"`
	ChatID        string                 `protobuf:"bytes,4,opt,name=ChatID,proto3" json:"ChatID,omitempty"`
	AccessToken   *string                `protobuf:"bytes,5,opt,name=AccessToken,proto3,oneof" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *Gateway) GetCompanyUUID() string {
	if x != nil {
		return x.CompanyUUID
	}
	return ""
}

func (x *Gateway) GetChannel() Channel {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return Channel_EMPTY_CHANNEL
}

func (x *Gateway) GetBotUUID() string {
	if x != nil {
		return x.BotUUID
	}
	return ""
}

func (x *Gateway) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

func (x *Gateway) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	FullName      string                 `protobuf:"bytes,5,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Photo         *File                  `protobuf:"bytes,6,opt,name=Photo,proto3" json:"Photo,omitempty"`
	IsBot         bool                   `protobuf:"varint,7,opt,name=IsBot,proto3" json:"IsBot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *Contact) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contact) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Contact) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Contact) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Contact) GetPhoto() *File {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *Contact) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *EventBody             `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	ReplyMenu     *ReplyMenu             `protobuf:"bytes,2,opt,name=ReplyMenu,proto3" json:"ReplyMenu,omitempty"`
	ChatMenu      *ChatMenu              `protobuf:"bytes,3,opt,name=ChatMenu,proto3" json:"ChatMenu,omitempty"`
	Contact       *Contact               `protobuf:"bytes,4,opt,name=Contact,proto3" json:"Contact,omitempty"`
	Options       *EventOptions          `protobuf:"bytes,5,opt,name=Options,proto3" json:"Options,omitempty"`
	Files         []*File                `protobuf:"bytes,6,rep,name=Files,proto3" json:"Files,omitempty"`
	Location      *EventLocation         `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	CallbackQuery *CallbackQuery         `protobuf:"bytes,8,opt,name=CallbackQuery,proto3" json:"CallbackQuery,omitempty"`
	MsgID         *string                `protobuf:"bytes,9,opt,name=MsgID,proto3,oneof" json:"MsgID,omitempty"`
	MsgIDEdited   *string                `protobuf:"bytes,10,opt,name=MsgIDEdited,proto3,oneof" json:"MsgIDEdited,omitempty"`
	UTM           []*UTM                 `protobuf:"bytes,11,rep,name=UTM,proto3" json:"UTM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *Content) GetBody() *EventBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Content) GetReplyMenu() *ReplyMenu {
	if x != nil {
		return x.ReplyMenu
	}
	return nil
}

func (x *Content) GetChatMenu() *ChatMenu {
	if x != nil {
		return x.ChatMenu
	}
	return nil
}

func (x *Content) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Content) GetOptions() *EventOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Content) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Content) GetLocation() *EventLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Content) GetCallbackQuery() *CallbackQuery {
	if x != nil {
		return x.CallbackQuery
	}
	return nil
}

func (x *Content) GetMsgID() string {
	if x != nil && x.MsgID != nil {
		return *x.MsgID
	}
	return ""
}

func (x *Content) GetMsgIDEdited() string {
	if x != nil && x.MsgIDEdited != nil {
		return *x.MsgIDEdited
	}
	return ""
}

func (x *Content) GetUTM() []*UTM {
	if x != nil {
		return x.UTM
	}
	return nil
}

type EventBody struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Formatted_Text string                 `protobuf:"bytes,2,opt,name=Formatted_Text,json=FormattedText,proto3" json:"Formatted_Text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventBody) Reset() {
	*x = EventBody{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBody) ProtoMessage() {}

func (x *EventBody) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBody.ProtoReflect.Descriptor instead.
func (*EventBody) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EventBody) GetFormatted_Text() string {
	if x != nil {
		return x.Formatted_Text
	}
	return ""
}

type ReplyMenu struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Keyboard        []*ButtonRow           `protobuf:"bytes,1,rep,name=Keyboard,proto3" json:"Keyboard,omitempty"`
	OneTimeKeyboard bool                   `protobuf:"varint,2,opt,name=OneTimeKeyboard,proto3" json:"OneTimeKeyboard,omitempty"`
	ResizeKeyboard  bool                   `protobuf:"varint,3,opt,name=ResizeKeyboard,proto3" json:"ResizeKeyboard,omitempty"`
	KeyboardInline  []*ButtonInlineRow     `protobuf:"bytes,4,rep,name=KeyboardInline,proto3" json:"KeyboardInline,omitempty"`
	RemoveKeyboard  bool                   `protobuf:"varint,5,opt,name=RemoveKeyboard,proto3" json:"RemoveKeyboard,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplyMenu) Reset() {
	*x = ReplyMenu{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMenu) ProtoMessage() {}

func (x *ReplyMenu) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMenu.ProtoReflect.Descriptor instead.
func (*ReplyMenu) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyMenu) GetKeyboard() []*ButtonRow {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

func (x *ReplyMenu) GetOneTimeKeyboard() bool {
	if x != nil {
		return x.OneTimeKeyboard
	}
	return false
}

func (x *ReplyMenu) GetResizeKeyboard() bool {
	if x != nil {
		return x.ResizeKeyboard
	}
	return false
}

func (x *ReplyMenu) GetKeyboardInline() []*ButtonInlineRow {
	if x != nil {
		return x.KeyboardInline
	}
	return nil
}

func (x *ReplyMenu) GetRemoveKeyboard() bool {
	if x != nil {
		return x.RemoveKeyboard
	}
	return false
}

type ChatMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatButton    *ChatButton            `protobuf:"bytes,1,opt,name=ChatButton,proto3" json:"ChatButton,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=Commands,proto3" json:"Commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMenu) Reset() {
	*x = ChatMenu{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMenu) ProtoMessage() {}

func (x *ChatMenu) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMenu.ProtoReflect.Descriptor instead.
func (*ChatMenu) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMenu) GetChatButton() *ChatButton {
	if x != nil {
		return x.ChatButton
	}
	return nil
}

func (x *ChatMenu) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type EventLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLocation) Reset() {
	*x = EventLocation{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLocation) ProtoMessage() {}

func (x *EventLocation) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLocation.ProtoReflect.Descriptor instead.
func (*EventLocation) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *EventLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EventLocation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EventLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type EventOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DisableNotification bool                   `protobuf:"varint,1,opt,name=DisableNotification,proto3" json:"DisableNotification,omitempty"`
	ParseMode           string                 `protobuf:"bytes,2,opt,name=ParseMode,proto3" json:"ParseMode,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *EventOptions) GetDisableNotification() bool {
	if x != nil {
		return x.DisableNotification
	}
	return false
}

func (x *EventOptions) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type CallbackQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	EventUUID     string                 `protobuf:"bytes,2,opt,name=EventUUID,proto3" json:"EventUUID,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackQuery) Reset() {
	*x = CallbackQuery{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackQuery) ProtoMessage() {}

func (x *CallbackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackQuery.ProtoReflect.Descriptor instead.
func (*CallbackQuery) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *CallbackQuery) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CallbackQuery) GetEventUUID() string {
	if x != nil {
		return x.EventUUID
	}
	return ""
}

func (x *CallbackQuery) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=Type,proto3,enum=kafkaMessages.FileType" json:"Type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	IsPreview     bool                   `protobuf:"varint,4,opt,name=IsPreview,proto3" json:"IsPreview,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=Filename,proto3" json:"Filename,omitempty"`
	MatrixUri     string                 `protobuf:"bytes,6,opt,name=MatrixUri,proto3" json:"MatrixUri,omitempty"`
	Duration      int32                  `protobuf:"varint,7,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Bucket        string                 `protobuf:"bytes,8,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Width         *int32                 `protobuf:"varint,9,opt,name=Width,proto3,oneof" json:"Width,omitempty"`
	Height        *int32                 `protobuf:"varint,10,opt,name=Height,proto3,oneof" json:"Height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *File) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *File) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_SOMETHING
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetIsPreview() bool {
	if x != nil {
		return x.IsPreview
	}
	return false
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetMatrixUri() string {
	if x != nil {
		return x.MatrixUri
	}
	return ""
}

func (x *File) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *File) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *File) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *File) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type Button struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Image          *File                  `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	URL            string                 `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	RequestContact bool                   `protobuf:"varint,4,opt,name=RequestContact,proto3" json:"RequestContact,omitempty"`
	CallbackData   string                 `protobuf:"bytes,5,opt,name=CallbackData,proto3" json:"CallbackData,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Button) Reset() {
	*x = Button{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Button) ProtoMessage() {}

func (x *Button) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Button.ProtoReflect.Descriptor instead.
func (*Button) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *Button) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Button) GetImage() *File {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Button) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *Button) GetRequestContact() bool {
	if x != nil {
		return x.RequestContact
	}
	return false
}

func (x *Button) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *Button) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ButtonRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buttons       []*Button              `protobuf:"bytes,1,rep,name=Buttons,proto3" json:"Buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonRow) Reset() {
	*x = ButtonRow{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonRow) ProtoMessage() {}

func (x *ButtonRow) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonRow.ProtoReflect.Descriptor instead.
func (*ButtonRow) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *ButtonRow) GetButtons() []*Button {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type ButtonInline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Image         *File                  `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	URL           string                 `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	CallbackData  string                 `protobuf:"bytes,4,opt,name=CallbackData,proto3" json:"CallbackData,omitempty"`
	WebAppURL     string                 `protobuf:"bytes,5,opt,name=WebAppURL,proto3" json:"WebAppURL,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonInline) Reset() {
	*x = ButtonInline{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonInline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonInline) ProtoMessage() {}

func (x *ButtonInline) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonInline.ProtoReflect.Descriptor instead.
func (*ButtonInline) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *ButtonInline) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ButtonInline) GetImage() *File {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ButtonInline) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *ButtonInline) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *ButtonInline) GetWebAppURL() string {
	if x != nil {
		return x.WebAppURL
	}
	return ""
}

func (x *ButtonInline) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ButtonInlineRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buttons       []*ButtonInline        `protobuf:"bytes,1,rep,name=Buttons,proto3" json:"Buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonInlineRow) Reset() {
	*x = ButtonInlineRow{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonInlineRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonInlineRow) ProtoMessage() {}

func (x *ButtonInlineRow) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonInlineRow.ProtoReflect.Descriptor instead.
func (*ButtonInlineRow) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *ButtonInlineRow) GetButtons() []*ButtonInline {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{15}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ChatButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatButton) Reset() {
	*x = ChatButton{}
	mi := &file_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatButton) ProtoMessage() {}

func (x *ChatButton) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatButton.ProtoReflect.Descriptor instead.
func (*ChatButton) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{16}
}

func (x *ChatButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatButton) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type SetEventState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventUUID     string                 `protobuf:"bytes,1,opt,name=EventUUID,proto3" json:"EventUUID,omitempty"`
	State         EventState             `protobuf:"varint,2,opt,name=State,proto3,enum=kafkaMessages.EventState" json:"State,omitempty"`
	UserUUID      string                 `protobuf:"bytes,3,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEventState) Reset() {
	*x = SetEventState{}
	mi := &file_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEventState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEventState) ProtoMessage() {}

func (x *SetEventState) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEventState.ProtoReflect.Descriptor instead.
func (*SetEventState) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{17}
}

func (x *SetEventState) GetEventUUID() string {
	if x != nil {
		return x.EventUUID
	}
	return ""
}

func (x *SetEventState) GetState() EventState {
	if x != nil {
		return x.State
	}
	return EventState_UNKNOWN_STATE
}

func (x *SetEventState) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type EventStates struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SetEventStates []*SetEventState       `protobuf:"bytes,1,rep,name=SetEventStates,proto3" json:"SetEventStates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventStates) Reset() {
	*x = EventStates{}
	mi := &file_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStates) ProtoMessage() {}

func (x *EventStates) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStates.ProtoReflect.Descriptor instead.
func (*EventStates) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{18}
}

func (x *EventStates) GetSetEventStates() []*SetEventState {
	if x != nil {
		return x.SetEventStates
	}
	return nil
}

type RoomOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	FileID        *string                `protobuf:"bytes,2,opt,name=FileID,proto3,oneof" json:"FileID,omitempty"`
	UsersAdd      []string               `protobuf:"bytes,3,rep,name=UsersAdd,proto3" json:"UsersAdd,omitempty"`
	UsersDel      []string               `protobuf:"bytes,4,rep,name=UsersDel,proto3" json:"UsersDel,omitempty"`
	UserUUID      *string                `protobuf:"bytes,5,opt,name=UserUUID,proto3,oneof" json:"UserUUID,omitempty"`
	RoomUUID      *string                `protobuf:"bytes,6,opt,name=RoomUUID,proto3,oneof" json:"RoomUUID,omitempty"`
	AddToAllRooms *bool                  `protobuf:"varint,7,opt,name=AddToAllRooms,proto3,oneof" json:"AddToAllRooms,omitempty"`
	UpdateMyRooms *bool                  `protobuf:"varint,8,opt,name=UpdateMyRooms,proto3,oneof" json:"UpdateMyRooms,omitempty"`
	UpdateRoom    *bool                  `protobuf:"varint,9,opt,name=UpdateRoom,proto3,oneof" json:"UpdateRoom,omitempty"`
	CreateRoom    *bool                  `protobuf:"varint,10,opt,name=CreateRoom,proto3,oneof" json:"CreateRoom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOptions) Reset() {
	*x = RoomOptions{}
	mi := &file_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOptions) ProtoMessage() {}

func (x *RoomOptions) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOptions.ProtoReflect.Descriptor instead.
func (*RoomOptions) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{19}
}

func (x *RoomOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RoomOptions) GetFileID() string {
	if x != nil && x.FileID != nil {
		return *x.FileID
	}
	return ""
}

func (x *RoomOptions) GetUsersAdd() []string {
	if x != nil {
		return x.UsersAdd
	}
	return nil
}

func (x *RoomOptions) GetUsersDel() []string {
	if x != nil {
		return x.UsersDel
	}
	return nil
}

func (x *RoomOptions) GetUserUUID() string {
	if x != nil && x.UserUUID != nil {
		return *x.UserUUID
	}
	return ""
}

func (x *RoomOptions) GetRoomUUID() string {
	if x != nil && x.RoomUUID != nil {
		return *x.RoomUUID
	}
	return ""
}

func (x *RoomOptions) GetAddToAllRooms() bool {
	if x != nil && x.AddToAllRooms != nil {
		return *x.AddToAllRooms
	}
	return false
}

func (x *RoomOptions) GetUpdateMyRooms() bool {
	if x != nil && x.UpdateMyRooms != nil {
		return *x.UpdateMyRooms
	}
	return false
}

func (x *RoomOptions) GetUpdateRoom() bool {
	if x != nil && x.UpdateRoom != nil {
		return *x.UpdateRoom
	}
	return false
}

func (x *RoomOptions) GetCreateRoom() bool {
	if x != nil && x.CreateRoom != nil {
		return *x.CreateRoom
	}
	return false
}

type TextTyping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextTyping) Reset() {
	*x = TextTyping{}
	mi := &file_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextTyping) ProtoMessage() {}

func (x *TextTyping) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextTyping.ProtoReflect.Descriptor instead.
func (*TextTyping) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{20}
}

type AttachFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        AttachFilesAction      `protobuf:"varint,1,opt,name=Action,proto3,enum=kafkaMessages.AttachFilesAction" json:"Action,omitempty"`
	TaskName      *string                `protobuf:"bytes,2,opt,name=TaskName,proto3,oneof" json:"TaskName,omitempty"`
	TaskID        *string                `protobuf:"bytes,3,opt,name=TaskID,proto3,oneof" json:"TaskID,omitempty"`
	File          *File                  `protobuf:"bytes,4,opt,name=File,proto3,oneof" json:"File,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFiles) Reset() {
	*x = AttachFiles{}
	mi := &file_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFiles) ProtoMessage() {}

func (x *AttachFiles) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFiles.ProtoReflect.Descriptor instead.
func (*AttachFiles) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{21}
}

func (x *AttachFiles) GetAction() AttachFilesAction {
	if x != nil {
		return x.Action
	}
	return AttachFilesAction_EMPTY_ACTION_ATTACH_FILES
}

func (x *AttachFiles) GetTaskName() string {
	if x != nil && x.TaskName != nil {
		return *x.TaskName
	}
	return ""
}

func (x *AttachFiles) GetTaskID() string {
	if x != nil && x.TaskID != nil {
		return *x.TaskID
	}
	return ""
}

func (x *AttachFiles) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type Archive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ArchiveAction          `protobuf:"varint,1,opt,name=Action,proto3,enum=kafkaMessages.ArchiveAction" json:"Action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Archive) Reset() {
	*x = Archive{}
	mi := &file_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Archive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Archive) ProtoMessage() {}

func (x *Archive) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Archive.ProtoReflect.Descriptor instead.
func (*Archive) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{22}
}

func (x *Archive) GetAction() ArchiveAction {
	if x != nil {
		return x.Action
	}
	return ArchiveAction_EMPTY_ACTION_ARCHIVE
}

type Cache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*CacheChanges        `protobuf:"bytes,1,rep,name=Changes,proto3" json:"Changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cache) Reset() {
	*x = Cache{}
	mi := &file_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache) ProtoMessage() {}

func (x *Cache) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache.ProtoReflect.Descriptor instead.
func (*Cache) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{23}
}

func (x *Cache) GetChanges() []*CacheChanges {
	if x != nil {
		return x.Changes
	}
	return nil
}

type CacheChanges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=Section,proto3" json:"Section,omitempty"`
	UserID        *string                `protobuf:"bytes,2,opt,name=UserID,proto3,oneof" json:"UserID,omitempty"`
	CarID         *string                `protobuf:"bytes,3,opt,name=CarID,proto3,oneof" json:"CarID,omitempty"`
	Connect       *string                `protobuf:"bytes,4,opt,name=Connect,proto3,oneof" json:"Connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheChanges) Reset() {
	*x = CacheChanges{}
	mi := &file_events_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheChanges) ProtoMessage() {}

func (x *CacheChanges) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheChanges.ProtoReflect.Descriptor instead.
func (*CacheChanges) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{24}
}

func (x *CacheChanges) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *CacheChanges) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *CacheChanges) GetCarID() string {
	if x != nil && x.CarID != nil {
		return *x.CarID
	}
	return ""
}

func (x *CacheChanges) GetConnect() string {
	if x != nil && x.Connect != nil {
		return *x.Connect
	}
	return ""
}

type UTM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTM) Reset() {
	*x = UTM{}
	mi := &file_events_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTM) ProtoMessage() {}

func (x *UTM) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTM.ProtoReflect.Descriptor instead.
func (*UTM) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{25}
}

func (x *UTM) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UTM) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\rkafkaMessages\"\xc9\x06\n" +
	"\x05Event\x12\x1c\n" +
	"\tEventUUID\x18\x01 \x01(\tR\tEventUUID\x120\n" +
	"\aGateway\x18\x02 \x01(\v2\x16.kafkaMessages.GatewayR\aGateway\x126\n" +
	"\tDirection\x18\x03 \x01(\x0e2\x18.kafkaMessages.DirectionR\tDirection\x12,\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x18.kafkaMessages.EventTypeR\x04Type\x12/\n" +
	"\x04From\x18\x05 \x01(\v2\x16.kafkaMessages.ContactH\x00R\x04From\x88\x01\x01\x125\n" +
	"\aContent\x18\x06 \x01(\v2\x16.kafkaMessages.ContentH\x01R\aContent\x88\x01\x01\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\tR\tCreatedAt\x12A\n" +
	"\vEventStates\x18\b \x01(\v2\x1a.kafkaMessages.EventStatesH\x02R\vEventStates\x88\x01\x01\x12A\n" +
	"\vRoomOptions\x18\t \x01(\v2\x1a.kafkaMessages.RoomOptionsH\x03R\vRoomOptions\x88\x01\x01\x12>\n" +
	"\n" +
	"TextTyping\x18\n" +
	" \x01(\v2\x19.kafkaMessages.TextTypingH\x04R\n" +
	"TextTyping\x88\x01\x01\x12A\n" +
	"\vAttachFiles\x18\v \x01(\v2\x1a.kafkaMessages.AttachFilesH\x05R\vAttachFiles\x88\x01\x01\x125\n" +
	"\aArchive\x18\f \x01(\v2\x16.kafkaMessages.ArchiveH\x06R\aArchive\x88\x01\x01\x12\x1d\n" +
	"\aReplyTo\x18\r \x01(\tH\aR\aReplyTo\x88\x01\x01\x12/\n" +
	"\x05Cache\x18\x0e \x01(\v2\x14.kafkaMessages.CacheH\bR\x05Cache\x88\x01\x01B\a\n" +
	"\x05_FromB\n" +
	"\n" +
	"\b_ContentB\x0e\n" +
	"\f_EventStatesB\x0e\n" +
	"\f_RoomOptionsB\r\n" +
	"\v_TextTypingB\x0e\n" +
	"\f_AttachFilesB\n" +
	"\n" +
	"\b_ArchiveB\n" +
	"\n" +
	"\b_ReplyToB\b\n" +
	"\x06_Cache\"\xd7\x01\n" +
	"\aGateway\x12 \n" +
	"\vCompanyUUID\x18\x01 \x01(\tR\vCompanyUUID\x125\n" +
	"\aChannel\x18\x02 \x01(\x0e2\x16.kafkaMessages.ChannelH\x00R\aChannel\x88\x01\x01\x12\x18\n" +
	"\aBotUUID\x18\x03 \x01(\tR\aBotUUID\x12\x16\n" +
	"\x06ChatID\x18\x04 \x01(\tR\x06ChatID\x12%\n" +
	"\vAccessToken\x18\x05 \x01(\tH\x01R\vAccessToken\x88\x01\x01B\n" +
	"\n" +
	"\b_ChannelB\x0e\n" +
	"\f_AccessToken\"\xc6\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Phone\x18\x02 \x01(\tR\x05Phone\x12\x1c\n" +
	"\tFirstName\x18\x03 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x04 \x01(\tR\bLastName\x12\x1a\n" +
	"\bFullName\x18\x05 \x01(\tR\bFullName\x12)\n" +
	"\x05Photo\x18\x06 \x01(\v2\x13.kafkaMessages.FileR\x05Photo\x12\x14\n" +
	"\x05IsBot\x18\a \x01(\bR\x05IsBot\"\xb8\x04\n" +
	"\aContent\x12,\n" +
	"\x04Body\x18\x01 \x01(\v2\x18.kafkaMessages.EventBodyR\x04Body\x126\n" +
	"\tReplyMenu\x18\x02 \x01(\v2\x18.kafkaMessages.ReplyMenuR\tReplyMenu\x123\n" +
	"\bChatMenu\x18\x03 \x01(\v2\x17.kafkaMessages.ChatMenuR\bChatMenu\x120\n" +
	"\aContact\x18\x04 \x01(\v2\x16.kafkaMessages.ContactR\aContact\x125\n" +
	"\aOptions\x18\x05 \x01(\v2\x1b.kafkaMessages.EventOptionsR\aOptions\x12)\n" +
	"\x05Files\x18\x06 \x03(\v2\x13.kafkaMessages.FileR\x05Files\x128\n" +
	"\bLocation\x18\a \x01(\v2\x1c.kafkaMessages.EventLocationR\bLocation\x12B\n" +
	"\rCallbackQuery\x18\b \x01(\v2\x1c.kafkaMessages.CallbackQueryR\rCallbackQuery\x12\x19\n" +
	"\x05MsgID\x18\t \x01(\tH\x00R\x05MsgID\x88\x01\x01\x12%\n" +
	"\vMsgIDEdited\x18\n" +
	" \x01(\tH\x01R\vMsgIDEdited\x88\x01\x01\x12$\n" +
	"\x03UTM\x18\v \x03(\v2\x12.kafkaMessages.UTMR\x03UTMB\b\n" +
	"\x06_MsgIDB\x0e\n" +
	"\f_MsgIDEdited\"F\n" +
	"\tEventBody\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12%\n" +
	"\x0eFormatted_Text\x18\x02 \x01(\tR\rFormattedText\"\x83\x02\n" +
	"\tReplyMenu\x124\n" +
	"\bKeyboard\x18\x01 \x03(\v2\x18.kafkaMessages.ButtonRowR\bKeyboard\x12(\n" +
	"\x0fOneTimeKeyboard\x18\x02 \x01(\bR\x0fOneTimeKeyboard\x12&\n" +
	"\x0eResizeKeyboard\x18\x03 \x01(\bR\x0eResizeKeyboard\x12F\n" +
	"\x0eKeyboardInline\x18\x04 \x03(\v2\x1e.kafkaMessages.ButtonInlineRowR\x0eKeyboardInline\x12&\n" +
	"\x0eRemoveKeyboard\x18\x05 \x01(\bR\x0eRemoveKeyboard\"y\n" +
	"\bChatMenu\x129\n" +
	"\n" +
	"ChatButton\x18\x01 \x01(\v2\x19.kafkaMessages.ChatButtonR\n" +
	"ChatButton\x122\n" +
	"\bCommands\x18\x02 \x03(\v2\x16.kafkaMessages.CommandR\bCommands\"y\n" +
	"\rEventLocation\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x1a\n" +
	"\bLatitude\x18\x03 \x01(\x02R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x04 \x01(\x02R\tLongitude\"^\n" +
	"\fEventOptions\x120\n" +
	"\x13DisableNotification\x18\x01 \x01(\bR\x13DisableNotification\x12\x1c\n" +
	"\tParseMode\x18\x02 \x01(\tR\tParseMode\"Q\n" +
	"\rCallbackQuery\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tEventUUID\x18\x02 \x01(\tR\tEventUUID\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data\"\xb0\x02\n" +
	"\x04File\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12+\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x17.kafkaMessages.FileTypeR\x04Type\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\x03R\x04Size\x12\x1c\n" +
	"\tIsPreview\x18\x04 \x01(\bR\tIsPreview\x12\x1a\n" +
	"\bFilename\x18\x05 \x01(\tR\bFilename\x12\x1c\n" +
	"\tMatrixUri\x18\x06 \x01(\tR\tMatrixUri\x12\x1a\n" +
	"\bDuration\x18\a \x01(\x05R\bDuration\x12\x16\n" +
	"\x06Bucket\x18\b \x01(\tR\x06Bucket\x12\x19\n" +
	"\x05Width\x18\t \x01(\x05H\x00R\x05Width\x88\x01\x01\x12\x1b\n" +
	"\x06Height\x18\n" +
	" \x01(\x05H\x01R\x06Height\x88\x01\x01B\b\n" +
	"\x06_WidthB\t\n" +
	"\a_Height\"\xb9\x01\n" +
	"\x06Button\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12)\n" +
	"\x05Image\x18\x02 \x01(\v2\x13.kafkaMessages.FileR\x05Image\x12\x10\n" +
	"\x03URL\x18\x03 \x01(\tR\x03URL\x12&\n" +
	"\x0eRequestContact\x18\x04 \x01(\bR\x0eRequestContact\x12\"\n" +
	"\fCallbackData\x18\x05 \x01(\tR\fCallbackData\x12\x12\n" +
	"\x04Type\x18\x06 \x01(\tR\x04Type\"<\n" +
	"\tButtonRow\x12/\n" +
	"\aButtons\x18\x01 \x03(\v2\x15.kafkaMessages.ButtonR\aButtons\"\xb5\x01\n" +
	"\fButtonInline\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12)\n" +
	"\x05Image\x18\x02 \x01(\v2\x13.kafkaMessages.FileR\x05Image\x12\x10\n" +
	"\x03URL\x18\x03 \x01(\tR\x03URL\x12\"\n" +
	"\fCallbackData\x18\x04 \x01(\tR\fCallbackData\x12\x1c\n" +
	"\tWebAppURL\x18\x05 \x01(\tR\tWebAppURL\x12\x12\n" +
	"\x04Type\x18\x06 \x01(\tR\x04Type\"H\n" +
	"\x0fButtonInlineRow\x125\n" +
	"\aButtons\x18\x01 \x03(\v2\x1b.kafkaMessages.ButtonInlineR\aButtons\"E\n" +
	"\aCommand\x12\x18\n" +
	"\aCommand\x18\x01 \x01(\tR\aCommand\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"2\n" +
	"\n" +
	"ChatButton\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\"z\n" +
	"\rSetEventState\x12\x1c\n" +
	"\tEventUUID\x18\x01 \x01(\tR\tEventUUID\x12/\n" +
	"\x05State\x18\x02 \x01(\x0e2\x19.kafkaMessages.EventStateR\x05State\x12\x1a\n" +
	"\bUserUUID\x18\x03 \x01(\tR\bUserUUID\"S\n" +
	"\vEventStates\x12D\n" +
	"\x0eSetEventStates\x18\x01 \x03(\v2\x1c.kafkaMessages.SetEventStateR\x0eSetEventStates\"\xcd\x03\n" +
	"\vRoomOptions\x12\x17\n" +
	"\x04Name\x18\x01 \x01(\tH\x00R\x04Name\x88\x01\x01\x12\x1b\n" +
	"\x06FileID\x18\x02 \x01(\tH\x01R\x06FileID\x88\x01\x01\x12\x1a\n" +
	"\bUsersAdd\x18\x03 \x03(\tR\bUsersAdd\x12\x1a\n" +
	"\bUsersDel\x18\x04 \x03(\tR\bUsersDel\x12\x1f\n" +
	"\bUserUUID\x18\x05 \x01(\tH\x02R\bUserUUID\x88\x01\x01\x12\x1f\n" +
	"\bRoomUUID\x18\x06 \x01(\tH\x03R\bRoomUUID\x88\x01\x01\x12)\n" +
	"\rAddToAllRooms\x18\a \x01(\bH\x04R\rAddToAllRooms\x88\x01\x01\x12)\n" +
	"\rUpdateMyRooms\x18\b \x01(\bH\x05R\rUpdateMyRooms\x88\x01\x01\x12#\n" +
	"\n" +
	"UpdateRoom\x18\t \x01(\bH\x06R\n" +
	"UpdateRoom\x88\x01\x01\x12#\n" +
	"\n" +
	"CreateRoom\x18\n" +
	" \x01(\bH\aR\n" +
	"CreateRoom\x88\x01\x01B\a\n" +
	"\x05_NameB\t\n" +
	"\a_FileIDB\v\n" +
	"\t_UserUUIDB\v\n" +
	"\t_RoomUUIDB\x10\n" +
	"\x0e_AddToAllRoomsB\x10\n" +
	"\x0e_UpdateMyRoomsB\r\n" +
	"\v_UpdateRoomB\r\n" +
	"\v_CreateRoom\"\f\n" +
	"\n" +
	"TextTyping\"\xd4\x01\n" +
	"\vAttachFiles\x128\n" +
	"\x06Action\x18\x01 \x01(\x0e2 .kafkaMessages.AttachFilesActionR\x06Action\x12\x1f\n" +
	"\bTaskName\x18\x02 \x01(\tH\x00R\bTaskName\x88\x01\x01\x12\x1b\n" +
	"\x06TaskID\x18\x03 \x01(\tH\x01R\x06TaskID\x88\x01\x01\x12,\n" +
	"\x04File\x18\x04 \x01(\v2\x13.kafkaMessages.FileH\x02R\x04File\x88\x01\x01B\v\n" +
	"\t_TaskNameB\t\n" +
	"\a_TaskIDB\a\n" +
	"\x05_File\"?\n" +
	"\aArchive\x124\n" +
	"\x06Action\x18\x01 \x01(\x0e2\x1c.kafkaMessages.ArchiveActionR\x06Action\">\n" +
	"\x05Cache\x125\n" +
	"\aChanges\x18\x01 \x03(\v2\x1b.kafkaMessages.CacheChangesR\aChanges\"\xa0\x01\n" +
	"\fCacheChanges\x12\x18\n" +
	"\aSection\x18\x01 \x01(\tR\aSection\x12\x1b\n" +
	"\x06UserID\x18\x02 \x01(\tH\x00R\x06UserID\x88\x01\x01\x12\x19\n" +
	"\x05CarID\x18\x03 \x01(\tH\x01R\x05CarID\x88\x01\x01\x12\x1d\n" +
	"\aConnect\x18\x04 \x01(\tH\x02R\aConnect\x88\x01\x01B\t\n" +
	"\a_UserIDB\b\n" +
	"\x06_CarIDB\n" +
	"\n" +
	"\b_Connect\"/\n" +
	"\x03UTM\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value*\xcb\x01\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aMESSAGE\x10\x01\x12\f\n" +
	"\bCALLBACK\x10\x02\x12\r\n" +
	"\tEVT_STATE\x10\x03\x12\x10\n" +
	"\fROOM_OPTIONS\x10\x04\x12\x0f\n" +
	"\vTEXT_TYPING\x10\x05\x12\x10\n" +
	"\fATTACH_FILES\x10\x06\x12\v\n" +
	"\aARCHIVE\x10\a\x12\v\n" +
	"\aNEW_BOT\x10\b\x12\f\n" +
	"\bNEW_CHAT\x10\t\x12\x10\n" +
	"\fMESSAGE_EDIT\x10\n" +
	"\x12\r\n" +
	"\tDATA_SIGN\x10\v\x12\t\n" +
	"\x05CACHE\x10\f*(\n" +
	"\tDirection\x12\f\n" +
	"\bINCOMING\x10\x00\x12\r\n" +
	"\tOUTCOMING\x10\x01*N\n" +
	"\bFileType\x12\r\n" +
	"\tSOMETHING\x10\x00\x12\t\n" +
	"\x05PHOTO\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\a\n" +
	"\x03DOC\x10\x03\x12\t\n" +
	"\x05AUDIO\x10\x04\x12\t\n" +
	"\x05VIDEO\x10\x05*\x82\x01\n" +
	"\aChannel\x12\x11\n" +
	"\rEMPTY_CHANNEL\x10\x00\x12\f\n" +
	"\bTELEGRAM\x10\x01\x12\x06\n" +
	"\x02VK\x10\x02\x12\b\n" +
	"\x04WABA\x10\x03\x12\a\n" +
	"\x03WEB\x10\x04\x12\f\n" +
	"\bWHATSAPP\x10\x05\x12\t\n" +
	"\x05AVITO\x10\x06\x12\a\n" +
	"\x03MAX\x10\a\x12\f\n" +
	"\bMAX_USER\x10\b\x12\v\n" +
	"\aCOMPANY\x10\t*Y\n" +
	"\n" +
	"EventState\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\b\n" +
	"\x04SENT\x10\x02\x12\f\n" +
	"\bRECEIVED\x10\x03\x12\b\n" +
	"\x04READ\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x05*O\n" +
	"\x11AttachFilesAction\x12\x1d\n" +
	"\x19EMPTY_ACTION_ATTACH_FILES\x10\x00\x12\f\n" +
	"\bTASK_ADD\x10\x01\x12\r\n" +
	"\tTASK_DONE\x10\x02*W\n" +
	"\rArchiveAction\x12\x18\n" +
	"\x14EMPTY_ACTION_ARCHIVE\x10\x00\x12\x13\n" +
	"\x0fMOVE_TO_ARCHIVE\x10\x01\x12\x17\n" +
	"\x13RETURN_FROM_ARCHIVE\x10\x02B\x12Z\x10./;kafkaMessagesb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_events_proto_goTypes = []any{
	(EventType)(0),          // 0: kafkaMessages.EventType
	(Direction)(0),          // 1: kafkaMessages.Direction
	(FileType)(0),           // 2: kafkaMessages.FileType
	(Channel)(0),            // 3: kafkaMessages.Channel
	(EventState)(0),         // 4: kafkaMessages.EventState
	(AttachFilesAction)(0),  // 5: kafkaMessages.AttachFilesAction
	(ArchiveAction)(0),      // 6: kafkaMessages.ArchiveAction
	(*Event)(nil),           // 7: kafkaMessages.Event
	(*Gateway)(nil),         // 8: kafkaMessages.Gateway
	(*Contact)(nil),         // 9: kafkaMessages.Contact
	(*Content)(nil),         // 10: kafkaMessages.Content
	(*EventBody)(nil),       // 11: kafkaMessages.EventBody
	(*ReplyMenu)(nil),       // 12: kafkaMessages.ReplyMenu
	(*ChatMenu)(nil),        // 13: kafkaMessages.ChatMenu
	(*EventLocation)(nil),   // 14: kafkaMessages.EventLocation
	(*EventOptions)(nil),    // 15: kafkaMessages.EventOptions
	(*CallbackQuery)(nil),   // 16: kafkaMessages.CallbackQuery
	(*File)(nil),            // 17: kafkaMessages.File
	(*Button)(nil),          // 18: kafkaMessages.Button
	(*ButtonRow)(nil),       // 19: kafkaMessages.ButtonRow
	(*ButtonInline)(nil),    // 20: kafkaMessages.ButtonInline
	(*ButtonInlineRow)(nil), // 21: kafkaMessages.ButtonInlineRow
	(*Command)(nil),         // 22: kafkaMessages.Command
	(*ChatButton)(nil),      // 23: kafkaMessages.ChatButton
	(*SetEventState)(nil),   // 24: kafkaMessages.SetEventState
	(*EventStates)(nil),     // 25: kafkaMessages.EventStates
	(*RoomOptions)(nil),     // 26: kafkaMessages.RoomOptions
	(*TextTyping)(nil),      // 27: kafkaMessages.TextTyping
	(*AttachFiles)(nil),     // 28: kafkaMessages.AttachFiles
	(*Archive)(nil),         // 29: kafkaMessages.Archive
	(*Cache)(nil),           // 30: kafkaMessages.Cache
	(*CacheChanges)(nil),    // 31: kafkaMessages.CacheChanges
	(*UTM)(nil),             // 32: kafkaMessages.UTM
}
var file_events_proto_depIdxs = []int32{
	8,  // 0: kafkaMessages.Event.Gateway:type_name -> kafkaMessages.Gateway
	1,  // 1: kafkaMessages.Event.Direction:type_name -> kafkaMessages.Direction
	0,  // 2: kafkaMessages.Event.Type:type_name -> kafkaMessages.EventType
	9,  // 3: kafkaMessages.Event.From:type_name -> kafkaMessages.Contact
	10, // 4: kafkaMessages.Event.Content:type_name -> kafkaMessages.Content
	25, // 5: kafkaMessages.Event.EventStates:type_name -> kafkaMessages.EventStates
	26, // 6: kafkaMessages.Event.RoomOptions:type_name -> kafkaMessages.RoomOptions
	27, // 7: kafkaMessages.Event.TextTyping:type_name -> kafkaMessages.TextTyping
	28, // 8: kafkaMessages.Event.AttachFiles:type_name -> kafkaMessages.AttachFiles
	29, // 9: kafkaMessages.Event.Archive:type_name -> kafkaMessages.Archive
	30, // 10: kafkaMessages.Event.Cache:type_name -> kafkaMessages.Cache
	3,  // 11: kafkaMessages.Gateway.Channel:type_name -> kafkaMessages.Channel
	17, // 12: kafkaMessages.Contact.Photo:type_name -> kafkaMessages.File
	11, // 13: kafkaMessages.Content.Body:type_name -> kafkaMessages.EventBody
	12, // 14: kafkaMessages.Content.ReplyMenu:type_name -> kafkaMessages.ReplyMenu
	13, // 15: kafkaMessages.Content.ChatMenu:type_name -> kafkaMessages.ChatMenu
	9,  // 16: kafkaMessages.Content.Contact:type_name -> kafkaMessages.Contact
	15, // 17: kafkaMessages.Content.Options:type_name -> kafkaMessages.EventOptions
	17, // 18: kafkaMessages.Content.Files:type_name -> kafkaMessages.File
	14, // 19: kafkaMessages.Content.Location:type_name -> kafkaMessages.EventLocation
	16, // 20: kafkaMessages.Content.CallbackQuery:type_name -> kafkaMessages.CallbackQuery
	32, // 21: kafkaMessages.Content.UTM:type_name -> kafkaMessages.UTM
	19, // 22: kafkaMessages.ReplyMenu.Keyboard:type_name -> kafkaMessages.ButtonRow
	21, // 23: kafkaMessages.ReplyMenu.KeyboardInline:type_name -> kafkaMessages.ButtonInlineRow
	23, // 24: kafkaMessages.ChatMenu.ChatButton:type_name -> kafkaMessages.ChatButton
	22, // 25: kafkaMessages.ChatMenu.Commands:type_name -> kafkaMessages.Command
	2,  // 26: kafkaMessages.File.Type:type_name -> kafkaMessages.FileType
	17, // 27: kafkaMessages.Button.Image:type_name -> kafkaMessages.File
	18, // 28: kafkaMessages.ButtonRow.Buttons:type_name -> kafkaMessages.Button
	17, // 29: kafkaMessages.ButtonInline.Image:type_name -> kafkaMessages.File
	20, // 30: kafkaMessages.ButtonInlineRow.Buttons:type_name -> kafkaMessages.ButtonInline
	4,  // 31: kafkaMessages.SetEventState.State:type_name -> kafkaMessages.EventState
	24, // 32: kafkaMessages.EventStates.SetEventStates:type_name -> kafkaMessages.SetEventState
	5,  // 33: kafkaMessages.AttachFiles.Action:type_name -> kafkaMessages.AttachFilesAction
	17, // 34: kafkaMessages.AttachFiles.File:type_name -> kafkaMessages.File
	6,  // 35: kafkaMessages.Archive.Action:type_name -> kafkaMessages.ArchiveAction
	31, // 36: kafkaMessages.Cache.Changes:type_name -> kafkaMessages.CacheChanges
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_events_proto_msgTypes[19].OneofWrappers = []any{}
	file_events_proto_msgTypes[21].OneofWrappers = []any{}
	file_events_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
