//ver. 0.0.2

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: payload.proto

package kafkaMessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Body          *PayloadBody           `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	Meta          *PayloadMeta           `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Payload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payload) GetBody() *PayloadBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Payload) GetMeta() *PayloadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PayloadBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadBody) Reset() {
	*x = PayloadBody{}
	mi := &file_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadBody) ProtoMessage() {}

func (x *PayloadBody) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadBody.ProtoReflect.Descriptor instead.
func (*PayloadBody) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PayloadBody) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type PayloadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUUID   string                 `protobuf:"bytes,1,opt,name=CompanyUUID,proto3" json:"CompanyUUID,omitempty"`
	BotUUID       string                 `protobuf:"bytes,2,opt,name=BotUUID,proto3" json:"BotUUID,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,3,opt,name=ReplyTo,proto3" json:"ReplyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadMeta) Reset() {
	*x = PayloadMeta{}
	mi := &file_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadMeta) ProtoMessage() {}

func (x *PayloadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadMeta.ProtoReflect.Descriptor instead.
func (*PayloadMeta) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadMeta) GetCompanyUUID() string {
	if x != nil {
		return x.CompanyUUID
	}
	return ""
}

func (x *PayloadMeta) GetBotUUID() string {
	if x != nil {
		return x.BotUUID
	}
	return ""
}

func (x *PayloadMeta) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

var File_payload_proto protoreflect.FileDescriptor

const file_payload_proto_rawDesc = "" +
	"\n" +
	"\rpayload.proto\x12\rkafkaMessages\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\aPayload\x12\x1c\n" +
	"\tEventName\x18\x01 \x01(\tR\tEventName\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12.\n" +
	"\x04Body\x18\x03 \x01(\v2\x1a.kafkaMessages.PayloadBodyR\x04Body\x12.\n" +
	"\x04Meta\x18\x04 \x01(\v2\x1a.kafkaMessages.PayloadMetaR\x04Meta\"I\n" +
	"\vPayloadBody\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\"c\n" +
	"\vPayloadMeta\x12 \n" +
	"\vCompanyUUID\x18\x01 \x01(\tR\vCompanyUUID\x12\x18\n" +
	"\aBotUUID\x18\x02 \x01(\tR\aBotUUID\x12\x18\n" +
	"\aReplyTo\x18\x03 \x01(\tR\aReplyToB\x12Z\x10./;kafkaMessagesb\x06proto3"

var (
	file_payload_proto_rawDescOnce sync.Once
	file_payload_proto_rawDescData []byte
)

func file_payload_proto_rawDescGZIP() []byte {
	file_payload_proto_rawDescOnce.Do(func() {
		file_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)))
	})
	return file_payload_proto_rawDescData
}

var file_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payload_proto_goTypes = []any{
	(*Payload)(nil),               // 0: kafkaMessages.Payload
	(*PayloadBody)(nil),           // 1: kafkaMessages.PayloadBody
	(*PayloadMeta)(nil),           // 2: kafkaMessages.PayloadMeta
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_payload_proto_depIdxs = []int32{
	3, // 0: kafkaMessages.Payload.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: kafkaMessages.Payload.Body:type_name -> kafkaMessages.PayloadBody
	2, // 2: kafkaMessages.Payload.Meta:type_name -> kafkaMessages.PayloadMeta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payload_proto_init() }
func file_payload_proto_init() {
	if File_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_proto_goTypes,
		DependencyIndexes: file_payload_proto_depIdxs,
		MessageInfos:      file_payload_proto_msgTypes,
	}.Build()
	File_payload_proto = out.File
	file_payload_proto_goTypes = nil
	file_payload_proto_depIdxs = nil
}
