// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: payload.proto

package kafkaMessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,2,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	ApiUuid       string                 `protobuf:"bytes,3,opt,name=api_uuid,json=apiUuid,proto3" json:"api_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiParams) Reset() {
	*x = ApiParams{}
	mi := &file_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiParams) ProtoMessage() {}

func (x *ApiParams) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiParams.ProtoReflect.Descriptor instead.
func (*ApiParams) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

func (x *ApiParams) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ApiParams) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *ApiParams) GetApiUuid() string {
	if x != nil {
		return x.ApiUuid
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Params        *ApiParams             `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Body          *PayloadBody           `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Payload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payload) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Payload) GetBody() *PayloadBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type PayloadBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadBody) Reset() {
	*x = PayloadBody{}
	mi := &file_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadBody) ProtoMessage() {}

func (x *PayloadBody) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadBody.ProtoReflect.Descriptor instead.
func (*PayloadBody) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payload_proto protoreflect.FileDescriptor

const file_payload_proto_rawDesc = "" +
	"\n" +
	"\rpayload.proto\x12\rkafkaMessages\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\tApiParams\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12!\n" +
	"\fcompany_uuid\x18\x02 \x01(\tR\vcompanyUuid\x12\x19\n" +
	"\bapi_uuid\x18\x03 \x01(\tR\aapiUuid\"\xc5\x01\n" +
	"\aPayload\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x120\n" +
	"\x06params\x18\x03 \x01(\v2\x18.kafkaMessages.ApiParamsR\x06params\x12.\n" +
	"\x04body\x18\x04 \x01(\v2\x1a.kafkaMessages.PayloadBodyR\x04body\"'\n" +
	"\vPayloadBody\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x12Z\x10./;kafkaMessagesb\x06proto3"

var (
	file_payload_proto_rawDescOnce sync.Once
	file_payload_proto_rawDescData []byte
)

func file_payload_proto_rawDescGZIP() []byte {
	file_payload_proto_rawDescOnce.Do(func() {
		file_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)))
	})
	return file_payload_proto_rawDescData
}

var file_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payload_proto_goTypes = []any{
	(*ApiParams)(nil),             // 0: kafkaMessages.ApiParams
	(*Payload)(nil),               // 1: kafkaMessages.Payload
	(*PayloadBody)(nil),           // 2: kafkaMessages.PayloadBody
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_payload_proto_depIdxs = []int32{
	3, // 0: kafkaMessages.Payload.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: kafkaMessages.Payload.params:type_name -> kafkaMessages.ApiParams
	2, // 2: kafkaMessages.Payload.body:type_name -> kafkaMessages.PayloadBody
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payload_proto_init() }
func file_payload_proto_init() {
	if File_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_proto_goTypes,
		DependencyIndexes: file_payload_proto_depIdxs,
		MessageInfos:      file_payload_proto_msgTypes,
	}.Build()
	File_payload_proto = out.File
	file_payload_proto_goTypes = nil
	file_payload_proto_depIdxs = nil
}
