// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: core_svc.proto

package coreService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_AddApi_FullMethodName     = "/coreService.CoreService/AddApi"
	CoreService_GetApi_FullMethodName     = "/coreService.CoreService/GetApi"
	CoreService_GetFullApi_FullMethodName = "/coreService.CoreService/GetFullApi"
	CoreService_UpdateApi_FullMethodName  = "/coreService.CoreService/UpdateApi"
	CoreService_DeleteApi_FullMethodName  = "/coreService.CoreService/DeleteApi"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService provides API management operations.
type CoreServiceClient interface {
	// AddApi adds a new API with the given parameters
	AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*Api, error)
	// GetApi retrieves APIs based on the given parameters
	GetApi(ctx context.Context, in *GetApiReq, opts ...grpc.CallOption) (*GetApiRes, error)
	// GetFullApi retrieves full API details
	GetFullApi(ctx context.Context, in *GetFullApiReq, opts ...grpc.CallOption) (*ApiFull, error)
	// UpdateApi updates an existing API with the given parameters
	UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*Api, error)
	// DeleteApi deletes an API with the given parameters
	DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*Api, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Api)
	err := c.cc.Invoke(ctx, CoreService_AddApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetApi(ctx context.Context, in *GetApiReq, opts ...grpc.CallOption) (*GetApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiRes)
	err := c.cc.Invoke(ctx, CoreService_GetApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetFullApi(ctx context.Context, in *GetFullApiReq, opts ...grpc.CallOption) (*ApiFull, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiFull)
	err := c.cc.Invoke(ctx, CoreService_GetFullApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*Api, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Api)
	err := c.cc.Invoke(ctx, CoreService_UpdateApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CoreService_DeleteApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations should embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService provides API management operations.
type CoreServiceServer interface {
	// AddApi adds a new API with the given parameters
	AddApi(context.Context, *AddApiReq) (*Api, error)
	// GetApi retrieves APIs based on the given parameters
	GetApi(context.Context, *GetApiReq) (*GetApiRes, error)
	// GetFullApi retrieves full API details
	GetFullApi(context.Context, *GetFullApiReq) (*ApiFull, error)
	// UpdateApi updates an existing API with the given parameters
	UpdateApi(context.Context, *UpdateApiReq) (*Api, error)
	// DeleteApi deletes an API with the given parameters
	DeleteApi(context.Context, *DeleteApiReq) (*emptypb.Empty, error)
}

// UnimplementedCoreServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) AddApi(context.Context, *AddApiReq) (*Api, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddApi not implemented")
}
func (UnimplementedCoreServiceServer) GetApi(context.Context, *GetApiReq) (*GetApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApi not implemented")
}
func (UnimplementedCoreServiceServer) GetFullApi(context.Context, *GetFullApiReq) (*ApiFull, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullApi not implemented")
}
func (UnimplementedCoreServiceServer) UpdateApi(context.Context, *UpdateApiReq) (*Api, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedCoreServiceServer) DeleteApi(context.Context, *DeleteApiReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApi not implemented")
}
func (UnimplementedCoreServiceServer) testEmbeddedByValue() {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_AddApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).AddApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_AddApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).AddApi(ctx, req.(*AddApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetApi(ctx, req.(*GetApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetFullApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetFullApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetFullApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetFullApi(ctx, req.(*GetFullApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateApi(ctx, req.(*UpdateApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeleteApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteApi(ctx, req.(*DeleteApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coreService.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddApi",
			Handler:    _CoreService_AddApi_Handler,
		},
		{
			MethodName: "GetApi",
			Handler:    _CoreService_GetApi_Handler,
		},
		{
			MethodName: "GetFullApi",
			Handler:    _CoreService_GetFullApi_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _CoreService_UpdateApi_Handler,
		},
		{
			MethodName: "DeleteApi",
			Handler:    _CoreService_DeleteApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core_svc.proto",
}
