// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: core_messages.proto

package coreService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Token         bool                   `protobuf:"varint,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Api) Reset() {
	*x = Api{}
	mi := &file_core_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api) ProtoMessage() {}

func (x *Api) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api.ProtoReflect.Descriptor instead.
func (*Api) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Api) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Api) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Api) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Api) GetToken() bool {
	if x != nil {
		return x.Token
	}
	return false
}

type ApiFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Subscriptions []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiFull) Reset() {
	*x = ApiFull{}
	mi := &file_core_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiFull) ProtoMessage() {}

func (x *ApiFull) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiFull.ProtoReflect.Descriptor instead.
func (*ApiFull) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ApiFull) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ApiFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApiFull) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiFull) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApiFull) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type ApiParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,2,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	ApiUuid       string                 `protobuf:"bytes,3,opt,name=api_uuid,json=apiUuid,proto3" json:"api_uuid,omitempty"`
	IdmUserUuid   string                 `protobuf:"bytes,4,opt,name=idm_user_uuid,json=idmUserUuid,proto3" json:"idm_user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiParams) Reset() {
	*x = ApiParams{}
	mi := &file_core_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiParams) ProtoMessage() {}

func (x *ApiParams) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiParams.ProtoReflect.Descriptor instead.
func (*ApiParams) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ApiParams) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ApiParams) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *ApiParams) GetApiUuid() string {
	if x != nil {
		return x.ApiUuid
	}
	return ""
}

func (x *ApiParams) GetIdmUserUuid() string {
	if x != nil {
		return x.IdmUserUuid
	}
	return ""
}

type AddApiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ApiParams             `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddApiReq) Reset() {
	*x = AddApiReq{}
	mi := &file_core_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddApiReq) ProtoMessage() {}

func (x *AddApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddApiReq.ProtoReflect.Descriptor instead.
func (*AddApiReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AddApiReq) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AddApiReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddApiReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddApiReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetApiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ApiParams             `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiReq) Reset() {
	*x = GetApiReq{}
	mi := &file_core_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiReq) ProtoMessage() {}

func (x *GetApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiReq.ProtoReflect.Descriptor instead.
func (*GetApiReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetApiReq) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetApiRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           []*Api                 `protobuf:"bytes,1,rep,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiRes) Reset() {
	*x = GetApiRes{}
	mi := &file_core_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiRes) ProtoMessage() {}

func (x *GetApiRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiRes.ProtoReflect.Descriptor instead.
func (*GetApiRes) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetApiRes) GetApi() []*Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type GetFullApiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ApiParams             `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullApiReq) Reset() {
	*x = GetFullApiReq{}
	mi := &file_core_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullApiReq) ProtoMessage() {}

func (x *GetFullApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullApiReq.ProtoReflect.Descriptor instead.
func (*GetFullApiReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetFullApiReq) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type UpdateApiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ApiParams             `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Token         *string                `protobuf:"bytes,4,opt,name=token,proto3,oneof" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApiReq) Reset() {
	*x = UpdateApiReq{}
	mi := &file_core_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApiReq) ProtoMessage() {}

func (x *UpdateApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApiReq.ProtoReflect.Descriptor instead.
func (*UpdateApiReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateApiReq) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UpdateApiReq) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateApiReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateApiReq) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type DeleteApiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ApiParams             `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiReq) Reset() {
	*x = DeleteApiReq{}
	mi := &file_core_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiReq) ProtoMessage() {}

func (x *DeleteApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiReq.ProtoReflect.Descriptor instead.
func (*DeleteApiReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteApiReq) GetParams() *ApiParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type PresignUrlRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XAmxTagging   string                 `protobuf:"bytes,4,opt,name=x_amx_tagging,json=xAmxTagging,proto3" json:"x_amx_tagging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUrlRes) Reset() {
	*x = PresignUrlRes{}
	mi := &file_core_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUrlRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUrlRes) ProtoMessage() {}

func (x *PresignUrlRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUrlRes.ProtoReflect.Descriptor instead.
func (*PresignUrlRes) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{9}
}

func (x *PresignUrlRes) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *PresignUrlRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignUrlRes) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PresignUrlRes) GetXAmxTagging() string {
	if x != nil {
		return x.XAmxTagging
	}
	return ""
}

var File_core_messages_proto protoreflect.FileDescriptor

const file_core_messages_proto_rawDesc = "" +
	"\n" +
	"\x13core_messages.proto\x12\vcoreService\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x03Api\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05token\x18\x04 \x01(\bR\x05token\"\x91\x01\n" +
	"\aApiFull\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\"\x90\x01\n" +
	"\tApiParams\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12!\n" +
	"\fcompany_uuid\x18\x02 \x01(\tR\vcompanyUuid\x12\x19\n" +
	"\bapi_uuid\x18\x03 \x01(\tR\aapiUuid\x12\"\n" +
	"\ridm_user_uuid\x18\x04 \x01(\tR\vidmUserUuid\"\x89\x01\n" +
	"\tAddApiReq\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.coreService.ApiParamsR\x06params\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\";\n" +
	"\tGetApiReq\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.coreService.ApiParamsR\x06params\"/\n" +
	"\tGetApiRes\x12\"\n" +
	"\x03api\x18\x01 \x03(\v2\x10.coreService.ApiR\x03api\"?\n" +
	"\rGetFullApiReq\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.coreService.ApiParamsR\x06params\"\xbf\x01\n" +
	"\fUpdateApiReq\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.coreService.ApiParamsR\x06params\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\x04 \x01(\tH\x02R\x05token\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_token\">\n" +
	"\fDeleteApiReq\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.coreService.ApiParamsR\x06params\"v\n" +
	"\rPresignUrlRes\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\"\n" +
	"\rx_amx_tagging\x18\x04 \x01(\tR\vxAmxTaggingB\x10Z\x0e./;coreServiceb\x06proto3"

var (
	file_core_messages_proto_rawDescOnce sync.Once
	file_core_messages_proto_rawDescData []byte
)

func file_core_messages_proto_rawDescGZIP() []byte {
	file_core_messages_proto_rawDescOnce.Do(func() {
		file_core_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_messages_proto_rawDesc), len(file_core_messages_proto_rawDesc)))
	})
	return file_core_messages_proto_rawDescData
}

var file_core_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_messages_proto_goTypes = []any{
	(*Api)(nil),           // 0: coreService.Api
	(*ApiFull)(nil),       // 1: coreService.ApiFull
	(*ApiParams)(nil),     // 2: coreService.ApiParams
	(*AddApiReq)(nil),     // 3: coreService.AddApiReq
	(*GetApiReq)(nil),     // 4: coreService.GetApiReq
	(*GetApiRes)(nil),     // 5: coreService.GetApiRes
	(*GetFullApiReq)(nil), // 6: coreService.GetFullApiReq
	(*UpdateApiReq)(nil),  // 7: coreService.UpdateApiReq
	(*DeleteApiReq)(nil),  // 8: coreService.DeleteApiReq
	(*PresignUrlRes)(nil), // 9: coreService.PresignUrlRes
}
var file_core_messages_proto_depIdxs = []int32{
	2, // 0: coreService.AddApiReq.params:type_name -> coreService.ApiParams
	2, // 1: coreService.GetApiReq.params:type_name -> coreService.ApiParams
	0, // 2: coreService.GetApiRes.api:type_name -> coreService.Api
	2, // 3: coreService.GetFullApiReq.params:type_name -> coreService.ApiParams
	2, // 4: coreService.UpdateApiReq.params:type_name -> coreService.ApiParams
	2, // 5: coreService.DeleteApiReq.params:type_name -> coreService.ApiParams
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_core_messages_proto_init() }
func file_core_messages_proto_init() {
	if File_core_messages_proto != nil {
		return
	}
	file_core_messages_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_messages_proto_rawDesc), len(file_core_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_messages_proto_goTypes,
		DependencyIndexes: file_core_messages_proto_depIdxs,
		MessageInfos:      file_core_messages_proto_msgTypes,
	}.Build()
	File_core_messages_proto = out.File
	file_core_messages_proto_goTypes = nil
	file_core_messages_proto_depIdxs = nil
}
