// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: core_svc.proto

package coreService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_svc_proto protoreflect.FileDescriptor

const file_core_svc_proto_rawDesc = "" +
	"\n" +
	"\x0ecore_svc.proto\x12\vcoreService\x1a\x13core_messages.proto2\x98\x02\n" +
	"\vcoreService\x12_\n" +
	"\x13InvoiceHandlersList\x12#.coreService.InvoiceHandlersListReq\x1a#.coreService.InvoiceHandlersListRes\x12M\n" +
	"\rUpdateProduct\x12\x1d.coreService.UpdateProductReq\x1a\x1d.coreService.UpdateProductRes\x12Y\n" +
	"\x11DeleteProductByID\x12!.coreService.DeleteProductByIdReq\x1a!.coreService.DeleteProductByIdResB\x10Z\x0e./;coreServiceb\x06proto3"

var file_core_svc_proto_goTypes = []any{
	(*InvoiceHandlersListReq)(nil), // 0: coreService.InvoiceHandlersListReq
	(*UpdateProductReq)(nil),       // 1: coreService.UpdateProductReq
	(*DeleteProductByIdReq)(nil),   // 2: coreService.DeleteProductByIdReq
	(*InvoiceHandlersListRes)(nil), // 3: coreService.InvoiceHandlersListRes
	(*UpdateProductRes)(nil),       // 4: coreService.UpdateProductRes
	(*DeleteProductByIdRes)(nil),   // 5: coreService.DeleteProductByIdRes
}
var file_core_svc_proto_depIdxs = []int32{
	0, // 0: coreService.coreService.InvoiceHandlersList:input_type -> coreService.InvoiceHandlersListReq
	1, // 1: coreService.coreService.UpdateProduct:input_type -> coreService.UpdateProductReq
	2, // 2: coreService.coreService.DeleteProductByID:input_type -> coreService.DeleteProductByIdReq
	3, // 3: coreService.coreService.InvoiceHandlersList:output_type -> coreService.InvoiceHandlersListRes
	4, // 4: coreService.coreService.UpdateProduct:output_type -> coreService.UpdateProductRes
	5, // 5: coreService.coreService.DeleteProductByID:output_type -> coreService.DeleteProductByIdRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_svc_proto_init() }
func file_core_svc_proto_init() {
	if File_core_svc_proto != nil {
		return
	}
	file_core_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_svc_proto_rawDesc), len(file_core_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_svc_proto_goTypes,
		DependencyIndexes: file_core_svc_proto_depIdxs,
	}.Build()
	File_core_svc_proto = out.File
	file_core_svc_proto_goTypes = nil
	file_core_svc_proto_depIdxs = nil
}
