// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: core_messages.proto

package coreService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceHandler) Reset() {
	*x = InvoiceHandler{}
	mi := &file_core_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceHandler) ProtoMessage() {}

func (x *InvoiceHandler) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceHandler.ProtoReflect.Descriptor instead.
func (*InvoiceHandler) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InvoiceHandler) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InvoiceHandler) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InvoiceHandler) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceHandler) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InvoiceHandlersListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceHandlersListReq) Reset() {
	*x = InvoiceHandlersListReq{}
	mi := &file_core_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceHandlersListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceHandlersListReq) ProtoMessage() {}

func (x *InvoiceHandlersListReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceHandlersListReq.ProtoReflect.Descriptor instead.
func (*InvoiceHandlersListReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{1}
}

type InvoiceHandlersListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handlers      []*InvoiceHandler      `protobuf:"bytes,1,rep,name=Handlers,proto3" json:"Handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceHandlersListRes) Reset() {
	*x = InvoiceHandlersListRes{}
	mi := &file_core_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceHandlersListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceHandlersListRes) ProtoMessage() {}

func (x *InvoiceHandlersListRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceHandlersListRes.ProtoReflect.Descriptor instead.
func (*InvoiceHandlersListRes) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{2}
}

func (x *InvoiceHandlersListRes) GetHandlers() []*InvoiceHandler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_core_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_core_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRes) Reset() {
	*x = UpdateProductRes{}
	mi := &file_core_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRes) ProtoMessage() {}

func (x *UpdateProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRes.ProtoReflect.Descriptor instead.
func (*UpdateProductRes) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductRes) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type DeleteProductByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdReq) Reset() {
	*x = DeleteProductByIdReq{}
	mi := &file_core_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdReq) ProtoMessage() {}

func (x *DeleteProductByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdReq.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdReq) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductByIdReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type DeleteProductByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdRes) Reset() {
	*x = DeleteProductByIdRes{}
	mi := &file_core_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdRes) ProtoMessage() {}

func (x *DeleteProductByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdRes.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdRes) Descriptor() ([]byte, []int) {
	return file_core_messages_proto_rawDescGZIP(), []int{7}
}

var File_core_messages_proto protoreflect.FileDescriptor

const file_core_messages_proto_rawDesc = "" +
	"\n" +
	"\x13core_messages.proto\x12\vcoreService\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n" +
	"\x0eInvoiceHandler\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x18\n" +
	"\aVersion\x18\x04 \x01(\tR\aVersion\"\x18\n" +
	"\x16InvoiceHandlersListReq\"Q\n" +
	"\x16InvoiceHandlersListRes\x127\n" +
	"\bHandlers\x18\x01 \x03(\v2\x1b.coreService.InvoiceHandlerR\bHandlers\"\xe7\x01\n" +
	"\aProduct\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"|\n" +
	"\x10UpdateProductReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\"0\n" +
	"\x10UpdateProductRes\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"4\n" +
	"\x14DeleteProductByIdReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"\x16\n" +
	"\x14DeleteProductByIdResB\x10Z\x0e./;coreServiceb\x06proto3"

var (
	file_core_messages_proto_rawDescOnce sync.Once
	file_core_messages_proto_rawDescData []byte
)

func file_core_messages_proto_rawDescGZIP() []byte {
	file_core_messages_proto_rawDescOnce.Do(func() {
		file_core_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_messages_proto_rawDesc), len(file_core_messages_proto_rawDesc)))
	})
	return file_core_messages_proto_rawDescData
}

var file_core_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_core_messages_proto_goTypes = []any{
	(*InvoiceHandler)(nil),         // 0: coreService.InvoiceHandler
	(*InvoiceHandlersListReq)(nil), // 1: coreService.InvoiceHandlersListReq
	(*InvoiceHandlersListRes)(nil), // 2: coreService.InvoiceHandlersListRes
	(*Product)(nil),                // 3: coreService.Product
	(*UpdateProductReq)(nil),       // 4: coreService.UpdateProductReq
	(*UpdateProductRes)(nil),       // 5: coreService.UpdateProductRes
	(*DeleteProductByIdReq)(nil),   // 6: coreService.DeleteProductByIdReq
	(*DeleteProductByIdRes)(nil),   // 7: coreService.DeleteProductByIdRes
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_core_messages_proto_depIdxs = []int32{
	0, // 0: coreService.InvoiceHandlersListRes.Handlers:type_name -> coreService.InvoiceHandler
	8, // 1: coreService.Product.CreatedAt:type_name -> google.protobuf.Timestamp
	8, // 2: coreService.Product.UpdatedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_messages_proto_init() }
func file_core_messages_proto_init() {
	if File_core_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_messages_proto_rawDesc), len(file_core_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_messages_proto_goTypes,
		DependencyIndexes: file_core_messages_proto_depIdxs,
		MessageInfos:      file_core_messages_proto_msgTypes,
	}.Build()
	File_core_messages_proto = out.File
	file_core_messages_proto_goTypes = nil
	file_core_messages_proto_depIdxs = nil
}
