// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: core_svc.proto

package coreService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_svc_proto protoreflect.FileDescriptor

const file_core_svc_proto_rawDesc = "" +
	"\n" +
	"\x0ecore_svc.proto\x12\vcoreService\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13core_messages.proto2\xb5\x02\n" +
	"\vCoreService\x122\n" +
	"\x06AddApi\x12\x16.coreService.AddApiReq\x1a\x10.coreService.Api\x128\n" +
	"\x06GetApi\x12\x16.coreService.GetApiReq\x1a\x16.coreService.GetApiRes\x12>\n" +
	"\n" +
	"GetFullApi\x12\x1a.coreService.GetFullApiReq\x1a\x14.coreService.ApiFull\x128\n" +
	"\tUpdateApi\x12\x19.coreService.UpdateApiReq\x1a\x10.coreService.Api\x12>\n" +
	"\tDeleteApi\x12\x19.coreService.DeleteApiReq\x1a\x16.google.protobuf.EmptyB\x10Z\x0e./;coreServiceb\x06proto3"

var file_core_svc_proto_goTypes = []any{
	(*AddApiReq)(nil),     // 0: coreService.AddApiReq
	(*GetApiReq)(nil),     // 1: coreService.GetApiReq
	(*GetFullApiReq)(nil), // 2: coreService.GetFullApiReq
	(*UpdateApiReq)(nil),  // 3: coreService.UpdateApiReq
	(*DeleteApiReq)(nil),  // 4: coreService.DeleteApiReq
	(*Api)(nil),           // 5: coreService.Api
	(*GetApiRes)(nil),     // 6: coreService.GetApiRes
	(*ApiFull)(nil),       // 7: coreService.ApiFull
	(*emptypb.Empty)(nil), // 8: google.protobuf.Empty
}
var file_core_svc_proto_depIdxs = []int32{
	0, // 0: coreService.CoreService.AddApi:input_type -> coreService.AddApiReq
	1, // 1: coreService.CoreService.GetApi:input_type -> coreService.GetApiReq
	2, // 2: coreService.CoreService.GetFullApi:input_type -> coreService.GetFullApiReq
	3, // 3: coreService.CoreService.UpdateApi:input_type -> coreService.UpdateApiReq
	4, // 4: coreService.CoreService.DeleteApi:input_type -> coreService.DeleteApiReq
	5, // 5: coreService.CoreService.AddApi:output_type -> coreService.Api
	6, // 6: coreService.CoreService.GetApi:output_type -> coreService.GetApiRes
	7, // 7: coreService.CoreService.GetFullApi:output_type -> coreService.ApiFull
	5, // 8: coreService.CoreService.UpdateApi:output_type -> coreService.Api
	8, // 9: coreService.CoreService.DeleteApi:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_svc_proto_init() }
func file_core_svc_proto_init() {
	if File_core_svc_proto != nil {
		return
	}
	file_core_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_svc_proto_rawDesc), len(file_core_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_svc_proto_goTypes,
		DependencyIndexes: file_core_svc_proto_depIdxs,
	}.Build()
	File_core_svc_proto = out.File
	file_core_svc_proto_goTypes = nil
	file_core_svc_proto_depIdxs = nil
}
