// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Oleg Testov",
            "url": "https://github.com/testovoleg",
            "email": "o.testov@5systems.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/api": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Получение списка интеграций по компании",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Администрирование"
                ],
                "summary": "Получить список интеграций",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ApiDto"
                            }
                        }
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Добавление новой интеграции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Администрирование"
                ],
                "summary": "Добавить новую интеграцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    },
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddApiReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ApiDto"
                        }
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/admin/api/{API_UUID}": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Получение подробных данных по интеграции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Администрирование"
                ],
                "summary": "Получить данные по интеграции",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор интеграции",
                        "name": "API_UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ApiFullDto"
                        }
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Удаление интеграции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Администрирование"
                ],
                "summary": "Удалить интеграцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор интеграции",
                        "name": "API_UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Обновление данных интеграции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Администрирование"
                ],
                "summary": "Обновить интеграцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор интеграции",
                        "name": "API_UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateApiReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ApiDto"
                        }
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/example": {
            "post": {
                "description": "Пример запроса для получения данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2. Данные"
                ],
                "summary": "Получить данные по запросу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компании",
                        "name": "company_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор интеграции",
                        "name": "api_uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Авторизационные данные неверны или устарели",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/webhook": {
            "post": {
                "description": "Вызывается внешним сервисом для уведомления о событиях, на которые осуществлена подписка",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Уведомления"
                ],
                "summary": "Уведомление",
                "parameters": [
                    {
                        "description": "Тело уведомления",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddApiReqDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.ApiDto": {
            "type": "object",
            "properties": {
                "api_uuid": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "token": {
                    "type": "boolean"
                }
            }
        },
        "dto.ApiFullDto": {
            "type": "object",
            "properties": {
                "api_uuid": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateApiReqDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "httpErrors.RestError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {},
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "description": "Bearer token. Example: 'Bearer xxxxxxxxxxxxxxxx'",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "1. Администрирование"
        },
        {
            "name": "2. Данные"
        },
        {
            "name": "3. Уведомления"
        }
    ],
    "x-tagGroups": [
        {
            "name": "",
            "tags": [
                "1. Администрирование",
                "2. Данные",
                "3. Уведомления"
            ]
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
