package constants

const (
	GrpcPort             = "GRPC_PORT"
	HttpPort             = "HTTP_PORT"
	HttpBasePath         = "HTTP_BASEPATH"
	ConfigPath           = "CONFIG_PATH"
	KafkaBrokers         = "KAFKA_BROKERS"
	OTLEndpoint          = "OTL_ENDPOINT"
	RedisAddr            = "REDIS_ADDR"
	RedisPassword        = "REDIS_PASSWORD"
	RedisDB              = "REDIS_DB"
	RedisPoolSize        = "Redis_PoolSize"
	MongoDbURI           = "MONGO_URI"
	PostgresqlHost       = "POSTGRES_HOST"
	PostgresqlPort       = "POSTGRES_PORT"
	PostgresqlUser       = "POSTGRES_USER"
	PostgresqlPassword   = "POSTGRES_PASSWORD"
	PostgresqlDatabase   = "POSTGRES_DATABASE"
	KeycloakHost         = "KEYCLOAK_HOST"
	KeycloakRealm        = "KEYCLOAK_REALM"
	KeycloakClientId     = "KEYCLOAK_CLIENTID"
	KeycloakClientSecret = "KEYCLOAK_CLIENTSECRET"

	CoreServicePort = "CORESERVICE_PORT"
	coreServicePort = "coreService_PORT"

	GraphQLQuery = "GRAPHQL_QUERY"
	RedoclyJSON  = "REDOCLY_JSON"

	RoleSuperuser     = "Superuser"
	RoleAdministrator = "Administrator"
	RoleWebservice    = "Webservice"

	Yaml     = "yaml"
	Redis    = "redis"
	Kafka    = "kafka"
	Postgres = "postgres"
	MongoDB  = "mongo"

	GRPC     = "GRPC"
	SIZE     = "SIZE"
	URI      = "URI"
	STATUS   = "STATUS"
	HTTP     = "HTTP"
	ERROR    = "ERROR"
	METHOD   = "METHOD"
	METADATA = "METADATA"
	REQUEST  = "REQUEST"
	REPLY    = "REPLY"
	TIME     = "TIME"
	TRACEID  = "TRACEID"

	Topic     = "topic"
	Partition = "partition"
	Message   = "message"
	WorkerID  = "workerID"
	Offset    = "offset"
	Time      = "time"

	Page   = "page"
	Size   = "size"
	Search = "search"
	ID     = "id"

	ContextKeyCookie = "cookie"
	ContextKeyToken  = "token"

	AdminAPIURL = "ADMIN_API_URL"
	AuthAPIURL  = "AUTH_API_URL"
	APIUsername = "API_USERNAME"
	APIPassword = "API_PASSWORD"
)
